[package]
name = "upcall_service_time"
version = "0.1.0"
authors = ["Marshall Clyburn <mardev2013@gmail.com>"]
edition = "2018"

[lib]
name = "clockwise_upcall_service_time"
crate_type = ["dylib"]

[dependencies]
clockwise_common = { path = "../../../../clockwise/common" }
